### ISSUE TITLE
How to plugin persistent storage to store conversations?

### ISSUE THREAD

**Issue by bhushanvadgave** [palindromed/Bot-HandOff#24]
Currently provider.ts maintains an array of conversations. I want to make my bot stateless. For bot should be able to read, write and update conversations in some persistent storage.
Please help.

**Comment by liliankasem** [comment]
You can create your own class that implements the `provider` interface and make your own method of storage. An example of this is here where we are using mongodb:

[mongoose-provider.ts]( https://github.com/palindromed/Bot-HandOff/blob/npm-handoff/src/mongoose-provider.ts)
